
# cargo-vet config file

[cargo-vet]
version = "0.5"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.chromeos]
url = "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/main/cargo-vet/audits.toml?format=TEXT"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.icd-converter]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.19.0"
criteria = "safe-to-deploy"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.async-stream]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.async-stream-impl]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.66"
criteria = "safe-to-deploy"

[[exemptions.atomic]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.67"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.binascii]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.1.9"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.cookie]]
version = "0.16.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.devise]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.devise_codegen]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.devise_core]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.figment]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.generator]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.2"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.httpdate]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.25"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.2"
criteria = "safe-to-deploy"

[[exemptions.inlinable_string]]
version = "0.1.15"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.io-lifetimes]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.140"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.loom]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.mime]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.multer]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.4.1"
criteria = "safe-to-deploy"

[[exemptions.overload]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.pear]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pear_codegen]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.52"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2-diagnostics]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.ref-cast]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.ref-cast-impl]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.28"
criteria = "safe-to-deploy"

[[exemptions.rocket_codegen]]
version = "0.5.0-rc.2"
criteria = "safe-to-deploy"

[[exemptions.rocket_http]]
version = "0.5.0-rc.2"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.36.9"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.156"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.156"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.stable-pattern]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.state]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.20"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.26.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.7"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.11"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.16"
criteria = "safe-to-deploy"

[[exemptions.try-lock]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.ubyte]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.uncased]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.unicode-xid]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.want]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.44.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-deploy"
